/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11-rc-3/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("net.idlestate.gradle-duplicate-classes-check") version "1.2.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

tasks {
    checkForDuplicateClasses {
        configurationsToCheck(configurations.runtimeClasspath.get())
    }
}
