name: checkForDuplicateClasses

on:
  push:

permissions: write-all

env:
  GRADLE_OPTS: >-
    -Dorg.gradle.logging.stacktrace=all
    -Dorg.gradle.logging.level=info
    -Dorg.gradle.vfs.watch=false
    -Dorg.gradle.console=plain

jobs:

  checkForDuplicateClasses:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Demonstrate no problem without configuration-cache
        run: >-
          ./gradlew
          --no-configuration-cache
          checkForDuplicateClasses

      - name: Demonstrate problem with configuration cache
        run: >-
          ./gradlew
          --configuration-cache
          checkForDuplicateClasses
